version: 2

jobs:
  build:
    docker:
      - image: cimg/android:2023.09.1-node # gcloud is baked into this image
        auth:
          username: tdrhq
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./gradlew :sample:recordPaparazziDebug
      - run:
          name: Run screenshotbot on all sub-modules
          # This Gradle task is created from the
          # io.screenshotbot.gradle plugin.
          command: ./gradlew recordAndVerifyPaparazziDebugScreenshotbotCI
